---
title: "[Python 문법] 예외 처리"
excerpt: "0517 Python 예외 처리"

categories:
  - Python 문법
tags:
  - []

permalink: /python/lesson5-2/

toc: true
toc_sticky: ture

date: 2023-05-17
last_modified_at: 2023-06-02
---

## 구문 오류
`SyntaxError`

```python
# 오타가 일반적
# 프로그램 실행 전에 발생하는 오류
prnit(2)
```

## try ~ except

```python
try:
  number = input('원의 반지름(단, 정수)> ')
  pi = 3.14
  number = int(number)
  print('원의 반지름', number)
  print('원의 둘레', number*pi*2)
  print('원의 넓이', number**2 * pi)
    
except:
  print('정수를 입력해주세요.')

# 원의 반지름(단, 정수)> 3.5
# 정수를 입력해주세요.
```

```python
# pass 사용 가능
try:
  number = input('원의 반지름(단, 정수)> ')
  pi = 3.14
  number = int(number)
  print('원의 반지름', number)
  print('원의 둘레', number*pi*2)
  print('원의 넓이', number**2 * pi)
    
except:
  pass

# 원의 반지름(단, 정수)> 5cm
```

## try ~ except ~ else
```python
try:
  number = input('원의 반지름(단, 정수)> ')
  pi = 3.14
  number = int(number)

except:
  print('정수를 입력해주세요.')
  
else:
  print('원의 반지름', number)
  print('원의 둘레', number*pi*2)
  print('원의 넓이', number**2 * pi)

# 원의 반지름(단, 정수)> 3
# 원의 반지름 3
# 원의 둘레 18.84
# 원의 넓이 28.26
```

## try ~ except ~ else ~ finally

```python
try:
  number = input('원의 반지름(단, 정수)> ')
  pi = 3.14
  number = int(number)

except:
  print('정수를 입력해주세요.')

else:
  print('원의 반지름', number)
  print('원의 둘레', number*pi*2)
  print('원의 넓이', number**2 * pi)

finally:
  print('프로그램 정상 종료')

# 원의 반지름(단, 정수)> 4.5
# 정수를 입력해주세요.
# 프로그램 정상 종료
```

## 예외 객체
```python
# 예외 정보를 저장하는 객체
try:
  number = input('원의 반지름(단, 정수)> ')
  pi = 3.14
  number = int(number)
  print('원의 반지름', number)
  print('원의 둘레', number*pi*2)
  print('원의 넓이', number**2 * pi)

except Exception as exception:
  print('예외 종료: ', type(exception))
  print('예외 종료: ', exception)

# 원의 반지름(단, 정수)> 3.1
# 예외 종료:  <class 'ValueError'>
# 예외 종료:  invalid literal for int() with base 10: '4.c'
```

```python
# 여러가지 예외 상황 (2가지)
a = [1,2,3,4,5]
try:
  # 첫번째 예외 상황: 정수가 아닌 문자열 입력
  number = int(input('정수를 입력> '))
  # 두번째 예외 상황: 인덱스에 없는 정수 번호를 입력한 경우
  print('{}번째 요소는 {}입니다.'.format(number, a[number]))

except Exception  as exception:
  print('예외 종료: ', type(exception))
  print('예외 종료: ', exception)

# 정수를 입력> 9
# 예외 종료:  <class 'IndexError'>
# 예외 종료:  list index out of range
```


## 예외 구분

- 예상할 수 없는 예외도 대처

```python
a = [1,2,3,4,5]
try:
  # 첫번째 예외 상황: 정수가 아닌 문자열 입력
  number = int(input('정수를 입력> '))
  # 두번째 예외 상황: 인덱스에 없는 정수 번호를 입력한 경우
  print('{}번째 요소는 {}입니다.'.format(number, a[number]))
  sdff
except ValueError:
  print('정수를 입력하세요.')
except IndexError:
  print('인덱스 범위에 있는 정수를 입력하세요.')

# 예상할 수 없는 예외도 대처
except Exception as exception:
  print('예외 종료: ', exception)

# 정수를 입력> 3
# 3번째 요소는 4입니다.
# 예외 종료:  name 'sdff' is not defined
```

- 예외 강제 발생

```python
try:
  number = input('원의 반지름(단, 정수)> ')
  pi = 3.14
  number = int(number)
  print('원의 반지름', number)
  print('원의 둘레', number*pi*2)
  print('원의 넓이', number**2 * pi)
except:
  raise NotImplementedError

# 원의 반지름(단, 정수)> 45465.2
# NotImplementedError: 
```